# -*- coding: utf-8 -*-
"""Untitled42.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KV6FFb9uaSSrP_s9ih4UY6NB1dRhsQ7N
"""

import numpy as np
import torch
import torch.nn as nn
from sklearn.model_selection import train_test_split
from torch.utils.data import Dataset,DataLoader
from torch.optim import Adam

N=1000
X=np.random.randint(low=1,high=10,size=(N,16))
y=np.random.randint(low=0,high=2,size=(N,1))

X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2)

print(X_train.shape)
print(y_train.shape)

device=torch.device("cuda" if torch.cuda.is_available() else"cpu")

print(device)

class CustomDataset(Dataset):
  def __init__(self,X,y):
    self.X=X
    self.y=y
  def __len__(self):
    return len(self.X)
  def __getitem__(self, index):
    _,features=self.X.shape
    x = torch.tensor(self.X[index], dtype=torch.float32)
    y = torch.tensor(self.y[index])
    mean=0.0
    std=0.1
    noise=torch.randn_like(torch.tensor(x,dtype=torch.float32))*std+mean

    return x+noise,y

train_ds=CustomDataset(X_train,y_train)
test_ds=CustomDataset(X_test,y_test)
train_loader=DataLoader(train_ds,batch_size=8,shuffle=True)
test_loader=DataLoader(test_ds,batch_size=4)

for batch_feature,batch_label in iter(train_loader):
  batch_feature=torch.tensor(batch_feature,dtype=torch.float32)
  batch_label=torch.tensor(batch_label,dtype=torch.float32)
  print(batch_feature.shape)
  print(batch_label.shape)

class NeuralNetwork(nn.Module):
  def __init__(self):
    super().__init__()
    self.linear1=nn.Linear(16,32)
    self.act1=nn.ReLU()
    self.norm1=nn.BatchNorm1d(32)
    self.drop1=nn.Dropout(p=0.5)
    self.linear2=nn.Linear(32,16)
    self.act2=nn.ReLU()
    self.linear3=nn.Linear(16,1)
    self.act3=nn.Sigmoid()
  def forward(self,x):
    x=self.norm1(self.act1(self.linear1(x)))
    x=self.drop1(x)
    x=self.act2(self.linear2(x))
    x=self.act3(self.linear3(x))
    return x

#OLD
'''
model=NeuralNetwork().to(device)
learning_rate=0.01
criterion=nn.BCELoss()
optimizer=Adam(model.parameters(),lr=learning_rate)
epochs=50
for epoch in range(epochs):
  for batch_feature,batch_label in iter(train_loader):
    batch_feature=torch.tensor(batch_feature,dtype=torch.float32).to(device)
    batch_label=torch.tensor(batch_label,dtype=torch.float32).to(device)
    output=model(batch_feature)
    loss=criterion(output,batch_label)
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()
  print(f"Epoch {epoch+1}: Loss = {loss.item():.4f}")
  '''

#OLD
'''
model.eval()
correct=0
threshold=0.5
tot=0
with torch.no_grad():
  for batch_feature,batch_label in iter(test_loader):
    batch_feature=torch.tensor(batch_feature,dtype=torch.float32).to(device)
    batch_label=torch.tensor(batch_label,dtype=torch.float32).to(device)
    output=model(batch_feature)
    preds = (output > threshold).float()
    correct+=(preds==batch_label).sum().item()
    tot+=batch_label.shape[0]
print(correct/tot)
'''

#Implementation of Checkpoints,Early Stopping , Plotting Loss curves, LR_Scheduler(same code just some more changes)
from torch.optim.lr_scheduler import CosineAnnealingLR
class EarlyStopping:
    def __init__(self, patience=5, delta=0, path="best_model.pth"):
        self.patience = patience
        self.delta = delta
        self.path = path

        self.best_loss = float("inf")
        self.counter = 0
        self.early_stop = False

    def __call__(self, val_loss, model):

        if val_loss < self.best_loss - self.delta:

            self.best_loss = val_loss
            self.counter = 0

            torch.save(model.state_dict(), self.path)

        else:

            self.counter += 1

            if self.counter >= self.patience:
                self.early_stop = True


early_stopping = EarlyStopping(
    patience=5,
    path="best_model.pth"
)
train_loss_hist=[]
val_loss_hist=[]
model=NeuralNetwork().to(device)
learning_rate=0.01
criterion=nn.BCELoss()
optimizer=Adam(model.parameters(),lr=learning_rate)
scheduler=CosineAnnealingLR(optimizer=optimizer,T_max=50)
epochs=50

for epoch in range(epochs):
  model.train()
  epoch_loss=0
  for batch_features,batch_labels in iter(train_loader):
    batch_features=torch.tensor(batch_features,dtype=torch.float32).to(device)
    batch_labels=torch.tensor(batch_labels,dtype=torch.float32).to(device)
    output = model(batch_features)
    loss = criterion(output.float().view(-1,1), batch_labels.float().view(-1,1))
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()
    epoch_loss+=(loss.item()/len(train_loader))
  train_loss_hist.append(epoch_loss)
  model.eval()
  epoch_val_loss=0
  with torch.no_grad():
    for batch_features,batch_labels in iter(test_loader):
      batch_features=torch.tensor(batch_features,dtype=torch.float32).to(device)
      batch_labels=torch.tensor(batch_labels,dtype=torch.float32).to(device)
      outputs=model(batch_features)
      val_loss=criterion(outputs.float().view(-1,1),batch_labels.float().view(-1,1))
      epoch_val_loss+=(val_loss.item()/len(test_loader))
    val_loss_hist.append(epoch_val_loss)
  scheduler.step()
  early_stopping(val_loss_hist[-1],model)
  if early_stopping.early_stop:
    print(f"Early stopping at epoch {epoch+1}")
    break

import matplotlib.pyplot as plt

plt.figure(figsize=(8,5))

plt.plot(train_loss_hist, label="Training Loss")
plt.plot(val_loss_hist, label="Validation Loss")

plt.xlabel("Epoch")
plt.ylabel("Loss")
plt.title("Training vs Validation Loss")
plt.legend()
plt.grid(True)

plt.show()

from torch.serialization import MAP_LOCATION
model=NeuralNetwork()
model.load_state_dict(torch.load("/content/best_model.pth",map_location=device))
model.to(device)

from sklearn.metrics import roc_curve, roc_auc_score


y_true = []
y_score = []

model.eval()

with torch.no_grad():
    for x, y in test_loader:

        x = x.float().to(device)

        outputs = model(x)

        y_score.append(outputs.cpu().view(-1))
        y_true.append(y.view(-1))

y_true = torch.cat(y_true)
y_score = torch.cat(y_score)

fpr, tpr, thresholds = roc_curve(y_true, y_score)

auc = roc_auc_score(y_true, y_score)

plt.figure(figsize=(6,6))

plt.plot(fpr, tpr, label=f"AUC = {auc:.3f}")
plt.plot([0,1], [0,1], '--')

plt.xlabel("False Positive Rate")
plt.ylabel("True Positive Rate")
plt.title("ROC Curve")
plt.legend()
plt.show()

print(thresholds)

from sklearn.metrics import f1_score

for threshold in [0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9]:

    preds = (y_score >= threshold).int()

    print(
        threshold,
        f1_score(y_true, preds)
    )

